package com.astrodham.astroagent.planner

import com.google.gson.annotations.SerializedName

/**
 * Data models for the AI planner system.
 * These represent the actions the agent can execute on the device.
 */
object PlanModels {

    /**
     * Types of actions the agent can perform.
     */
    enum class ActionType {
        @SerializedName("open_app")    OPEN_APP,
        @SerializedName("tap")         TAP,
        @SerializedName("long_press")  LONG_PRESS,
        @SerializedName("swipe")       SWIPE,
        @SerializedName("type_text")   TYPE_TEXT,
        @SerializedName("wait")        WAIT,
        @SerializedName("back")        BACK,
        @SerializedName("home")        HOME,
        @SerializedName("scroll")      SCROLL,
        @SerializedName("read_screen") READ_SCREEN,
        @SerializedName("retry_action") RETRY_ACTION;

        companion object {
            fun fromString(value: String): ActionType? {
                return entries.find { it.name.equals(value, ignoreCase = true) }
                    ?: entries.find {
                        val serialized = it.declaringJavaClass.getField(it.name)
                            .getAnnotation(SerializedName::class.java)?.value
                        serialized == value
                    }
            }
        }
    }

    /**
     * A single planned action to be executed by the agent.
     */
    data class PlannedAction(
        /** The type of action to perform */
        @SerializedName("type")
        val type: String,

        /** Parameters for the action (keys depend on action type) */
        @SerializedName("params")
        val params: Map<String, String> = emptyMap(),

        /** Human-readable description of what this action does */
        @SerializedName("description")
        val description: String = ""
    ) {
        /** Parsed action type enum */
        val actionType: ActionType?
            get() = ActionType.fromString(type)

        /** Convenience accessors for common params */
        fun getParam(key: String): String? = params[key]
        fun getParamOrDefault(key: String, default: String): String = params[key] ?: default
    }

    /**
     * A complete execution plan generated by the AI.
     */
    data class Plan(
        /** Unique identifier for this plan */
        val id: String,

        /** Ordered list of actions to execute */
        val actions: List<PlannedAction>,

        /** The user's goal this plan aims to achieve */
        val goal: String,

        /** Timestamp of plan creation */
        val createdAt: Long = System.currentTimeMillis()
    ) {
        val actionCount: Int get() = actions.size
        val isEmpty: Boolean get() = actions.isEmpty()
    }
}
